### PR TITLE
✨ Disable an enabled pause and multiple pauses handling features added

### LINKED ISSUE #288: Add option to disable an enabled pause
"pausing a pause".

To prevent self guilt and worsening of a crisis, one should be able to say "hey Petals, I'm on a crisis right now, suspend the pause for a week"

### PR DESCRIPTION
**Pull request by markopex**
Switch button added next to "Pause time" button enables user to disable created pause. IsDisabled field added to the Pause model alongside unit tests. close #288

### CODE REVIEW

**Comment by LeoColman** [comment]
Ref: #244

**Comment by LeoColman** [comment]
Related: #244

**Comment by markopex** [comment]
The feature for handling multiple pauses has been implemented. `PauseRepository` has been modified to support working with multiple pauses, and unit tests have been updated to cover this new functionality.

Uploading Multiple pauses.mp4…

**Comment by LeoColman** [comment]
Thanks a lot for the contribution! I'll take it from here :)

**Comment by LeoColman** [comment]
Released :)
https://github.com/LeoColman/Petals/releases/tag/3.26.0

**Pull request merged**
